sudo: required
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - docker
jobs:
  include:
    - stage: import
      script:
        - scripts/import_questions.py

    - stage: test
      script:
        - echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_USER" --password-stdin

    - stage: build
      script:
        - docker build -t cmattoon/nremt-prep:latest .
        
    - stage: push
      script:
        - docker push cmattoon/nremt-prep:latest

stages:
  - name: import
    if: commit_message =~ /^import_questions\.py/ AND branch = master
  - name: test
  - name: build
  - name: push
    if: branch = master
    
